agenda_contact:
    resource: 'routing/contact.yml'
    prefix: /contact

agenda_phones:
    resource: 'routing/phones.yml'
    prefix: /phones

show_contacts:
    resource: 'routing/contact.yml'
    prefix: /show_contacts


edit_contacts:
    resource: 'routing/contact.yml'
    prefix: /edit_contacts

delete_contacts:
    resource: 'routing/contact.yml'
    prefix: /edit_contacts