agenda_contact:
    resource: 'routing/contact.yml'
    prefix: /contact

agenda_phones:
    resource: 'routing/phones.yml'
    prefix: /phones

:
    resource: 'routing/phones.yml'
    prefix: /phones

