agenda_contact:
    resource: 'routing/contact.yml'
    prefix: /contact

agenda_phones:
    resource: 'routing/phones.yml'
    prefix: /phones

show_contacts:
    resource: 'routing/contact.yml'
    prefix: /show

