
contact_new:
    path: /new
    defaults: {_controller: App\Controller\Agenda\DefaultController::new}


show_contacts:
    path: /show_contacts
    defaults: {_controller: App\Controller\Agenda\DefaultController::show}
