
contact_new:
    path: /new
    defaults: {_controller: App\Controller\Agenda\DefaultController::new}


contact_new:
    path: /new
    defaults: {_controller: App\Controller\Agenda\DefaultController::new}
