
contact_new:
    path: /new
    defaults: {_controller: App\Controller\Agenda\DefaultController::new}


show_contacts:
    path: /show_conta
    defaults: {_controller: App\Controller\Agenda\DefaultController::new}
