app_register:
    path: /register
    defaults: {_controller: App\Controller\RegistrationController::register}

app_loggin:
    path: /login
    defaults: {_controller: App\Controller\Security\SecurityController::login}


app_logout:
    path: /logout
    defaults: {_controller: App\Controller\Security\SecurityController::login}