app_register:
    path: /register
    defaults: {_controller: App\Controller\RegistrationController::register}

app_register:
    path: /register
    defaults: {_controller: App\Controller\RegistrationController::register}