phones_new:
    path: /phones
    defaults: {_controller: App\Controller\Agenda\PhoneController::phones}

show_phones:
    path: /show_phone
    defaults: {_controller: App\Controller\Agenda\DefaultController::show_contact}