
framework:
    router:
        utf8: true    
routes:       
index:   
    path: /
    controller: App\Controller\my_agendaController::index
        # Configure how to generate URLs in non-HTTP contexts, such as CLI commands.
        # See https://symfony.com/doc/current/routing.html#generating-urls-in-commands
        #default_uri: http://localhost
